print('Welcome to "sau"', end='')
print("Welcome to 'sau'")
print("~~~~~~~~~~~~~~~~~~")
print('Welcome to \'sau\'')
print("Welcome to \"dti\"")
print("~~~~~~~~~~~~~~~~~~")
print(4546)
print(4547.9445)
print(True)
print(False)
print(15 * 10 + 2)
print(True or False and False)